### ISSUE TITLE
Make FIELDS public

### ISSUE THREAD

**Issue by twiclo** [TedDriggs/field_names#3]
I'd like to be able to access these fields anywhere. If it's all the same to you I'd appreciate the change

**Comment by TedDriggs** [comment]
The documentation explains how to do this [here](https://github.com/TedDriggs/field_names#how-do-i-make-fields-or-variants-public).

That approach makes the decision of how to expose the field names entirely up to the deriving struct, which seems most appropriate to me since this crate is trying not to leave any trace of its use.
